[package]
name = "swaytitlers"
version = "0.1.0"
edition = "2021"
[dependencies]
swayipc = "3.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
